# Configuração básica do Eclipse Mosquitto (MQTT)
# Usado para comunicação interna entre Frigate e Double-Take

# Permitir conexões anônimas (sem senha) apenas na rede interna do docker
allow_anonymous true

# Escutar na porta padrão
listener 1883
